version: '3.9'

services:
  messenger:
    container_name: messenger
    image: messenger:0.1.0
    build: .
    environment:
      DATABASE_URL: "host=host.docker.internal user=postgres password=postgres dbname=postgres sslmode=disable"
      COGNITO_CLIENT_ID: "qiqoemp8hjlt1ar1qf1233o7t"
      COGNITO_USER_POOL_ID: "us-east-2_bGTPLFgM7"
      AWS_ACCESS_KEY_ID: AKIA53SEUVWTCL33UH4G
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-west-2
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
  