name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull thaironsilva/go-messenger:latest
      - name: Delete old docker container
        run: sudo docker rm -f go-messenger-container || true
      - name: Run docker container
        run: >-
          sudo docker run -d --name go-messenger-container \
            -e DATABASE_URL="${{secrets.DATABASE_URL}}" \
            -e COGNITO_CLIENT_ID=${{secrets.COGNITO_CLIENT_ID}} \
            -e COGNITO_USER_POOL_ID=${{secrets.COGNITO_USER_POOL_ID}} \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION='us-west-2' \
            -p 8080:8080 thaironsilva/go-messenger
      - name: Prune docker images
        run: sudo docker image prune -f
