name: Go Messenger

on: [push]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.6'

      - name: Get
        run: go get -d -v ./...

      - name: Build migrate
        run: go build ./cmd/migrate

      - name: Build app
        run: go build ./cmd/app

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: go test -v ./...
